# Generated by Django 5.2.7 on 2025-10-30 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип компонента')),
                ('description', models.TextField(blank=True, verbose_name='Описание типа')),
            ],
            options={
                'verbose_name': 'Тип компонента',
                'verbose_name_plural': 'Типы компонентов',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название производителя')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('specifications', models.JSONField(default=dict, verbose_name='Характеристики')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.componenttype', verbose_name='Тип компонента')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
            },
        ),
        migrations.CreateModel(
            name='PCConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название конфигурации')),
                ('description', models.TextField(blank=True, verbose_name='Описание конфигурации')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_configs', to='configurator.component', verbose_name='Корпус')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_configs', to='configurator.component', verbose_name='Процессор')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_configs', to='configurator.component', verbose_name='Видеокарта')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_configs', to='configurator.component', verbose_name='Материнская плата')),
                ('power_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psu_configs', to='configurator.component', verbose_name='Блок питания')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ram_configs', to='configurator.component', verbose_name='Оперативная память')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_configs', to='configurator.component', verbose_name='Накопитель')),
            ],
            options={
                'verbose_name': 'Конфигурация ПК',
                'verbose_name_plural': 'Конфигурации ПК',
            },
        ),
        migrations.CreateModel(
            name='BuildRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет')),
                ('notes', models.TextField(blank=True, verbose_name='Дополнительные пожелания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.pcconfiguration', verbose_name='Конфигурация')),
            ],
            options={
                'verbose_name': 'Запрос на сборку',
                'verbose_name_plural': 'Запросы на сборку',
            },
        ),
    ]
