# Generated by Django 5.2.7 on 2025-10-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, verbose_name='Характеристики'),
        ),
    ]
