# Generated by Django 5.2.8 on 2025-11-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_alter_component_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='components/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='manufacturers/', verbose_name='Логотип'),
        ),
    ]
