# Generated by Django 5.2.7 on 2025-12-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0004_component_user_manufacturer_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={},
        ),
        migrations.AlterModelOptions(
            name='componenttype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pcconfiguration',
            options={},
        ),
    ]
